services:
 nimbly:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: ${NIMBLY_CONTAINER_NAME:-nimbly-v1.1.0}
    working_dir: /var/www/nimbly
    volumes:
      - ../..:/var/www/nimbly
    ports:
      - 80:80
