services:
 nimbly:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    container_name: nimbly
    working_dir: /var/www/nimbly
    volumes:
      - ..:/var/www/nimbly
    ports:
      - 80:80
