[if item.type=boolean tpl=boolean-field]
[if item.type=date tpl=date-field]
[if item.type=file tpl=file-field]
[if item.type=fixed tpl=fixed-field]
[nop if item.type=gallery tpl=gallery-field]
[if item.type=image tpl=image-field]
[if item.type=name tpl=name-field]
[if item.type=select tpl=select-field]
[if item.type=text tpl=text-field]
[if item.type=textarea tpl=textarea-field]
[nop if item.type=block-html tpl=block-html-field]