[#module user forms#]
[#access feature=add-[#resource#],manage-content,manage-[#resource#],(any)_[#resource#]#]
[#set resource-name=[#resource#]#]
[#set _resource_url=[#base-url#]/nb-admin/[#resource#]#]
[#set page-title="[#text Add [#resource-name#]#]"#]
[#html#]
