[#set _ftype="[#item.type#]" overwrite#]
[#set _fname="[#item.key#]" overwrite#]
[#set _fvalue="[#get record.[#item.key#]#]" overwrite#]
[#set _fmodel="form_data.[#item.key#]" overwrite#]
[#set _ftitle="[#text [#field-name name="[#item.name#]"#]#]" overwrite#]