[#access feature=edit-[#resource-id#]#]
[#set _resource_url="[#base-url#]/nb-admin/[#resource-id#]"#]
[#set page-title="[#text Deleted records#] · [#resource-name [#resource-id#] plural#]"#]
[#post#]
[#html#]
