<?php

/**
 * Nimbly CLI — docker:init command
 *
 * Usage: php core/cli/nimbly.php docker:init [--update]
 *
 * Generates a Dockerfile and GitHub Actions workflow in ext/ so the project
 * can build and publish its own Docker image via CI.
 *
 * --update  Overwrite existing generated files (e.g. after a framework upgrade).
 */

if (php_sapi_name() !== 'cli') {
    die("nimbly.php must be run from the command line.\n");
}

if (!defined('BASE_DIR')) define('BASE_DIR', realpath(__DIR__ . '/../..') . '/');
require_once BASE_DIR . 'core/cli/helpers/output.php';

$update = in_array('--update', $argv);

// -------------------------------------------------------------------------
// Read NIMBLY_VERSION from package.json
// Full semver (e.g. "1.1.0") for git clone; major.minor (e.g. "1.1") for image tag
// -------------------------------------------------------------------------

$pkg = json_decode(file_get_contents(BASE_DIR . 'package.json'), true);
$full_version = $pkg['version'] ?? '1.1.0';
preg_match('/^(\d+)\.(\d+)\.(\d+)/', $full_version, $m);
$nimbly_version       = isset($m[0]) ? $m[0] : '1.1.0';   // 1.1.0 — for git clone tag
$nimbly_image_tag     = isset($m[1]) ? "{$m[1]}.{$m[2]}" : '1.1'; // 1.1 — for image FROM

// -------------------------------------------------------------------------
// Read APP_NAME from .env
// -------------------------------------------------------------------------

$env = [];
$env_file = BASE_DIR . '.env';
if (file_exists($env_file)) {
    foreach (file($env_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        if (str_starts_with(trim($line), '#')) continue;
        [$key, $val] = array_map('trim', explode('=', $line, 2) + [1 => '']);
        $env[$key] = $val;
    }
}

$site_name = $env['SITE_NAME'] ?? '';
$app_slug  = strtolower(trim(preg_replace('/[^a-z0-9]+/i', '-', $site_name), '-'));
if (empty($app_slug)) {
    $app_slug = 'my-app';
}

// -------------------------------------------------------------------------
// Derive GHCR image path from ext/ git remote, or prompt
// -------------------------------------------------------------------------

$ext_dir  = BASE_DIR . 'ext';
$image    = null;

if (is_dir($ext_dir . '/.git')) {
    $remote = trim(shell_exec('git -C ' . escapeshellarg($ext_dir) . ' remote get-url origin 2>/dev/null') ?? '');
    if (preg_match('#github\.com[:/]([^/]+)/([^/\.]+)#', $remote, $rm)) {
        $gh_org  = strtolower($rm[1]);
        $gh_repo = strtolower(rtrim($rm[2], '.git'));
        $image   = "ghcr.io/{$gh_org}/{$gh_repo}";
    }
}

if (!$image) {
    echo "Could not determine GitHub org from ext/ remote.\n";
    echo "Enter your GitHub org or username: ";
    $gh_org = trim(fgets(STDIN));
    $image  = "ghcr.io/{$gh_org}/{$app_slug}";
}

// -------------------------------------------------------------------------
// Generate files
// -------------------------------------------------------------------------

cli_section('docker:init');

$dockerfile_path = $ext_dir . '/Dockerfile';
$workflow_dir    = $ext_dir . '/.github/workflows';
$workflow_path   = $workflow_dir . '/docker-publish.yml';
$dockerignore_path = $ext_dir . '/.dockerignore';

$generated = [];
$skipped   = [];

function write_generated(string $path, string $content, bool $update, array &$generated, array &$skipped): void {
    if (file_exists($path) && !$update) {
        $skipped[] = $path;
        return;
    }
    $dir = dirname($path);
    if (!is_dir($dir)) mkdir($dir, 0755, true);
    file_put_contents($path, $content);
    $generated[] = $path;
}

// -- ext/Dockerfile --

$dockerfile = <<<DOCKERFILE
# Generated by ./nimbly docker:init — update with: ./nimbly docker:init --update
ARG NIMBLY_VERSION={$nimbly_version}

# Stage 1: build CSS/JS assets
FROM node:20-alpine AS builder
ARG NIMBLY_VERSION
RUN apk add --no-cache git
RUN git clone --depth 1 --branch v\${NIMBLY_VERSION} \\
    https://github.com/Nimbly-Web-Systems/nimbly-core.git /build
WORKDIR /build
RUN npm ci --silent
COPY . ./ext/
RUN npm run build

# Stage 2: production app image
FROM ghcr.io/nimbly-web-systems/nimbly-core:{$nimbly_image_tag}
COPY --from=builder /build/ext/ /var/www/nimbly/ext/
RUN chown -R www-data:www-data /var/www/nimbly/ext/
DOCKERFILE;

write_generated($dockerfile_path, $dockerfile . "\n", $update, $generated, $skipped);

// -- ext/.github/workflows/docker-publish.yml --

$workflow = <<<WORKFLOW
# Generated by ./nimbly docker:init — update with: ./nimbly docker:init --update
name: Build and publish

on:
  push:
    branches: [main, master]
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: {$image}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: NIMBLY_VERSION={$nimbly_version}
          tags: \${{ steps.meta.outputs.tags }}
          labels: \${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
WORKFLOW;

write_generated($workflow_path, $workflow . "\n", $update, $generated, $skipped);

// -- ext/.dockerignore --

$dockerignore = <<<DOCKERIGNORE
.git
.github
data
DOCKERIGNORE;

write_generated($dockerignore_path, $dockerignore . "\n", $update, $generated, $skipped);

// -------------------------------------------------------------------------
// Output
// -------------------------------------------------------------------------

foreach ($generated as $path) {
    echo cli_color('created', 'green') . '  ' . str_replace(BASE_DIR, '', $path) . "\n";
}
foreach ($skipped as $path) {
    echo cli_color('skipped', 'dim') . '  ' . str_replace(BASE_DIR, '', $path) . " (already exists — use --update to overwrite)\n";
}

echo "\n";
echo "Image: " . cli_color($image, 'bold') . "\n";
echo "Base:  " . cli_color("ghcr.io/nimbly-web-systems/nimbly-core:{$nimbly_version}", 'dim') . "\n";
echo "\n";
cli_tip("Commit the generated files in ext/ and push — GitHub Actions will build and publish the image automatically.");
cli_tip("After a framework upgrade, run ./nimbly docker:init --update to refresh the pinned version.");
echo "\n";
