[#access feature=edit-.navigation#]
[#managed-navigation-editor#]
[#set admin_tab=navigation#]
[#set admin_header_title="[#text Navigation#]"#]
[#set admin_header_subtitle="[#text Arrange the links visitors use to find your pages.#]"#]
[#set page-title="[#text Navigation#]"#]
[#html#]
