[#module user forms#]
[#access feature=import-[#resource-id#],manage-content,manage-[#resource-id#],(any)_[#resource-id#]#]
[#set _resource_url="[#base-url#]/nb-admin/[#resource-id#]"#]
[#set page-title="[#text Import [#resource-name [#resource-id#] plural#]#]"#]
[#html#]
